### ISSUE TITLE
Provide support to ingest data from a single data source into multiple Metadb instances

### ISSUE THREAD

**Issue by sbeltaine** [metadb-project/metadb#61]
We are currently sychronizing a Metadb Test instance with our FOLIO Test application server. We would like guidance on sychronizing our FOLIO application server data to two Metadb instances. This does not appear to be covered in the metadb documentation at https://metadb.dev/doc/ at this time.

**Comment by nassibnassar** [comment]
This is not currently supported, but I think it can be done if you are willing always to resync both Metadb instances together.

**Comment by nassibnassar** [comment]
@hutchinsonca
