### ISSUE TITLE
Performance metrics on intial synchronization and resynchronization processes

### ISSUE THREAD

**Issue by sbeltaine** [metadb-project/metadb#62]
As we test and configure our Metadb Test instance, which is currently ingesting data from our FOLIO Test instance, we are wondering what performance metrics to expect for our synchronization and resynchronization procedures. Addition an example to the documentation on metadb at https://metadb.dev/doc/ showing estimated initial sync and resync times given X associated data volume would be very helpful.

**Comment by nassibnassar** [comment]
I think there are too many variables to estimate this.  It might be possible very roughly as a DevOps activity using a similar source database, but I think it would be out of scope for this documentation.

**Comment by nassibnassar** [comment]
@hutchinsonca
