### ISSUE TITLE
Allow the Metadb administrator to specify which version of the folio-analytics SQL to be used and not require a new Metadb release

### ISSUE THREAD

**Issue by mdgatid** [metadb-project/metadb#71]
Currently when folio-analytics queries are updated, in order to have them used in a Metadb deployment we need to create a new release of Metadb. This enhancement would allow the version of SQL in folio-analytics to be specified at startup (either through config or command-line).

**Comment by nassibnassar** [comment]
Added in commit ae614ac8695b4d91207baac0b5c27882f65bca58 as build override via environment variable.  Example:
```
METADB_FOLIO='refs/tags/v1.7.7' ./build.sh
```
